  
version: "3"

services:
  db:
    image: postgres:10-alpine
    volumes:
      - /var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"