version: "3"
services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
